//
//  Question:
//    Each new term in the Fibonacci sequence is generated by adding the
//    previous two terms. By starting with 1 and 2, the first 10 terms will be:
//    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the
//    Fibonacci sequence whose values do not exceed four million, find the sum
//    of the even-valued terms.
//
//  Answer:
//    4613732
//

import Foundation

func problem2(max: Int) -> Int {
  var ctr: (last: Int, this: Int) = (1, 2)
  var total = 2

  while ctr.this < max {
    ctr = (ctr.this, ctr.this + ctr.last)

    if ctr.this % 2 == 0 {
      total += ctr.this
    }
  }

  return total
}
