PROJECT_PATH?=ProjectEuler.xcodeproj
PROJECT_NAME?=ProjectEuler

test:
	@echo "-----> Running tests"
	@xcodebuild test -project ${PROJECT_PATH} -scheme ${PROJECT_NAME} -destination 'platform=OS X,arch=x86_64'

.PHONY: test
