"""
Question:
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer:
	4613732
"""

from helpers.timer import print_timing


@print_timing
def problem2(upper_limit):
	total = 2
	last = 1
	this = 2

	while this < upper_limit:
		last, this = this, this + last

		if this % 2 == 0:
			total += this

	return total


if __name__ == "__main__":
	print(problem2(4000000))
